/**
 * @author amadeus.portes
 */
object Versions {
    const val gradle = "4.1.3"
    const val kotlin = "1.4.32"
    const val core = "1.3.2"
    const val appCompat = "1.2.0"
    const val material = "1.4.0"
    const val navigation = "2.3.5"
    const val lifecycle = "2.3.1"
    const val junit = "4.13.2"
    const val mockitoInline = "2.23.4"
    const val mockitoKotlin = "2.2.11"
    const val coreTesting = "2.1.0"
    const val coroutinesTest = "1.4.1"
    const val coroutinesCore = "1.4.2"
    const val hilt = "2.28-alpha"
    const val hiltViewModel = "1.0.0-alpha01"
    const val hiltPlugin = "2.31.2-alpha"
    const val timber = "4.7.1"
    const val retrofit = "2.9.0"
    const val coroutines = "1.4.3"
    const val moshi = "1.11.0"
    const val codegen = "1.10.0"
    const val interceptor = "4.7.2"
    const val lottie = "3.4.1"
    const val androidChart = "v3.1.0"
    const val swipeRefresh = "1.1.0"
    const val epoxy = "4.4.4"
    const val biometric = "1.0.1"
    const val firebaseAuth = "21.0.1"
    const val firebaseConfig = "21.0.1"
    const val googlePlayServices = "4.3.4"
    const val coroutinesPlayServices = "1.1.1"
    const val easyPermissions = "1.0.0"
    const val itext = "7.1.3"
}